### ISSUE TITLE
no module named pymongo

### ISSUE THREAD

**Issue by AmtelopeJoe** [phishontop/bloxsint#3]
Using Kali Linux 2023

Installed as per instructions

typed python3 main.py --target-id lexie_112511 --file roblox.txt

Traceback (most recent call last):
  File "/home/kali/bloxsint/main.py", line 1, in <module>
    from core.lookup import Lookup
  File "/home/kali/bloxsint/core/lookup.py", line 7, in <module>
    from .utilities.database import Database
  File "/home/kali/bloxsint/core/utilities/database.py", line 1, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'

I'm running it from the bloxsint directory. What am I doing wrong?

**Comment by phishontop** [comment]
pip install pymongo

**Comment by AmtelopeJoe** [comment]
Thanks for the quick reply. That fixed that error. Now when I run it against a roblox user, I get this:

──(kali㉿kali)-[~/bloxsint]
└─$ python3 main.py --target-id lexie_112511 --file roblox.txt   
Traceback (most recent call last):
  File "/home/kali/bloxsint/main.py", line 21, in <module>
    bloxsint = Lookup(roblox_id=int(target_id), args=args)
                                ^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'lexie_112511'

**Comment by phishontop** [comment]
enter just the roblox ID instead of "lexi_112511" it would become "112511"
